---
title: scalar_advection_poisson

# restart capability
restart = true 

#  number of timesteps
steps: 100
#  number of iterations
iterations: 200
# time step size
dt: 1.0e-2

# Square/cubic mesh generation parameters
# cells per side
cps: 3
# domain size
L: 1.0

relaxation_factor:
  u: 0.9
  v: 0.9
  w: 0.9
  p: 0.1

target_residual: 1.0e-10

# Frequency (in terms of timesteps) of writing solution to file
write_frequency: 50

# Fluid properties
viscocity : 1.0e-3


variables:
  n_variables: 5
  enable_cell_corrections: true
  variable_1:
    name: u
    type: central
  variable_2:
    name: v
    type: central
  variable_3:
    name: scalar
    type: central
  variable_4:
    name: p
    type: central
  variable_5:
    name: p_prime
    type: central

boundaries:
  n_boundaries: 4
  boundary_1: 
    name: left
    type: dirichlet
    value: 1
  boundary_2:
    name: right
    type: neumann
    value: 0
  boundary_3:
    name: bottom
    type: neumann
    value: 0
  boundary_4:
    name: top
    type: neumann
    value: 0
 