bases: 
  mpi_petsc: 
    defaults:
      mat_common: mat_common
      mat: mat_petsc
      vec_common: vec_common
      vec: vec_petsc
      solver_common: solver_common
      solver: solver_petsc
      parallel_env: parallel_env_mpi_petsc
      parallel_env_error: parallel_errors_mpi_petsc
      parallel_utils: parallel_utils_mpi
      read_config: read_config_yaml
      io: io_adios2
      io_setup: io_setup_adios2
    options:
      #component: [opt_1, opt_2, opt_3]
