.general_setup:
  before_script:
  except:
    variables:
      - $NIGHTLY
      - $A2_PERFORMANCE

.setup_gnu:
  before_script:
    - source setup_gitlab_runner_env
    - source ${GNU_SETUP} 32bit

.setup_intel:
  before_script:
    - source setup_gitlab_runner_env
    - source ${INTEL_SETUP} 32bit

.setup_cray:
  before_script:
    - source setup_gitlab_runner_env

.setup_cray_A2:
  tags:
    - ARCHER2
  variables:
    ON_COMPUTE: "TRUE"
    SLURM_job_name: gitlab-ci-job
    SLURM_account: i246
    SLURM_partition: serial
    SLURM_qos: serial
    SLURM_time: "00:10:00"
  before_script:
    - source ${CRAY_SETUP}

.test_common:
  artifacts:
    when: always
    reports:
      junit: tests/report.xml


#-----------------------------------------------------------------------------#

debug_build_gnu:
  extends: [.general_setup, .setup_gnu]
  script:
    - HOME=${CI_HOME} CMP=gnu BUILD=debug make all
  allow_failure: true

build_gnu:
  extends: [.general_setup, .setup_gnu]
  script:
    - HOME=${CI_HOME} CMP=gnu make obj
  artifacts:
    paths: [obj/]

test_gnu:
  needs: 
    - job: debug_build_gnu
      artifacts: true
  extends: [.general_setup, .setup_gnu, .test_common]
  script:
    - HOME=${CI_HOME} CMP=gnu BUILD=debug make tests

#-----------------------------------------------------------------------------#

debug_build_intel:
  extends: [.general_setup, .setup_intel]
  script:
    - HOME=${CI_HOME} CMP=intel BUILD=debug make all
  allow_failure: true

build_intel:
  extends: [.general_setup, .setup_intel]
  script:
    - HOME=${CI_HOME} CMP=intel make obj
  artifacts:
    paths: [obj/]

test_intel:
  needs: 
    - job: build_intel
      artifacts: true
  extends: [.general_setup, .setup_intel, .test_common]
  script:
    - HOME=${CI_HOME} CMP=intel make tests

#-----------------------------------------------------------------------------#

debug_build_intelx:
  extends: [.general_setup, .setup_intel]
  script:
    - HOME=${CI_HOME} CMP=intelx BUILD=debug make all
  allow_failure: true

build_intelx:
  extends: [.general_setup, .setup_intel]
  script:
    - HOME=${CI_HOME} CMP=intelx make obj
  artifacts:
    paths: [obj/]

test_intelx:
  needs: 
    - job: build_intelx
      artifacts: true
  extends: [.general_setup, .setup_intel, .test_common]
  script:
    - HOME=${CI_HOME} CMP=intelx make tests

#-----------------------------------------------------------------------------#
#don't run cray debug build because it fails on the CI
.debug_build_cray:
  extends: [.general_setup, .setup_cray]
  script:
    - HOME=${CI_HOME} cray_run_command "CMP=cray BUILD=debug make all"
  allow_failure: true

build_cray:
  extends: [.general_setup, .setup_cray]
  script:
    - HOME=${CI_HOME} cray_run_command "CMP=cray make obj"
  artifacts:
    paths: [obj/]

#don't run cray tests because slurm is broken on the CI
.test_cray:
  needs: 
    - job: build_cray
      artifacts: true
  extends: [.general_setup, .setup_cray, .test_common]
  script:
    - cray_run_command "slurmctld -vv"
    - cray_run_command "slurmd -vv"
    - HOME=${CI_HOME} cray_run_command "CMP=cray make tests"

#-----------------------------------------------------------------------------#

ARCHER2_trigger:
  extends: [.general_setup, .setup_cray_A2]
  variables:
    ON_COMPUTE: "FALSE"
  when: manual
  script:
    - echo "Manual trigger" 

debug_build_cray_A2:
  extends: [.general_setup, .setup_cray_A2]
  needs:
    - job: ARCHER2_trigger
  variables:
    SLURM_ntasks: 5
  script:
    - CMP=cray BUILD=debug make all
  allow_failure: true

build_cray_A2:
  extends: [.general_setup, .setup_cray_A2]
  needs:
    - job: ARCHER2_trigger
  variables:
    SLURM_ntasks: 5
  script:
    - CMP=cray make obj
  artifacts:
    paths: [obj/]

test_cray_A2:
  needs: 
    - job: build_cray_A2
      artifacts: true
    - job: ARCHER2_trigger
  extends: [.general_setup, .setup_cray_A2, .test_common]
  variables:
    SLURM_ntasks: 5
  script:
    - CMP=cray make tests

#-----------------------------------------------------------------------------#

lint_src:
  extends: [.general_setup]
  script: 
    - bash build_tools/lint.sh lint src
    - bash build_tools/lint.sh score_each_file src
  allow_failure: true

lint_tests:
  extends: [.general_setup]
  script: 
    - bash build_tools/lint.sh lint tests
    - bash build_tools/lint.sh score_each_file tests
  allow_failure: true

#-----------------------------------------------------------------------------#

generate_ford_docs:
  extends: [.general_setup]
  script:
    - make ford
  artifacts:
    paths:
      - doc
  allow_failure: true

generate_dev_guide:
  extends: [.general_setup]
  script:
    - make dev_guide
  artifacts:
    paths:
      - dev_guide/ccs_dev_guide.pdf
  allow_failure: true

#-----------------------------------------------------------------------------#

profile_gnu:
  needs: 
    - job: build_gnu
      artifacts: false
  extends: [.general_setup, .setup_gnu]
  script:
    - HOME=${CI_HOME} CMP=gnu PROFILE=yes make all
  artifacts:
    paths:
      - opt_info.txt
  allow_failure: true

profile_intel:
  needs: 
    - job: build_intel
      artifacts: false
  extends: [.general_setup, .setup_intel]
  script:
    - HOME=${CI_HOME} CMP=intel PROFILE=yes make all
  artifacts:
    paths:
      - obj/*.html
      - ./*.html
  allow_failure: true

.profile_cray:
  needs: 
    - job: build_cray
      artifacts: false
  extends: [.general_setup, .setup_cray]
  script:
    - HOME=${CI_HOME} cray_run_command "CMP=cray PROFILE=yes make all"
  artifacts:
    paths:
      - obj/*.lst
      - ./*.lst
  allow_failure: true

#-----------------------------------------------------------------------------#
# ARCHER2 performance

.setup_A2_perf:
  only:
    variables:
      - $A2_PERFORMANCE

# 1 node
A2_perf_1node:
  extends: [.setup_A2_perf, .setup_cray_A2]
  variables:
    SLURM_partition: standard
    SLURM_qos: lowpriority
    SLURM_time: "00:10:00"
    SLURM_ntasks_per_node: 128
    SLURM_nodes: 1
  script:
    - CMP=cray make -j all
    - export CPS=108
    - export NCORES=128
    - RUNTESTS=nightly/performance/test_tgv.yaml CMP=cray make tests
  artifacts:
    paths: [tests/nightly/performance/output*txt]

A2_perf_1node_database_update:
  extends: [.setup_A2_perf, .setup_cray_A2]
  needs:
    - job: A2_perf_1node
      artifacts: true
  variables:
    ON_COMPUTE: "FALSE"
  script:
    - git clone https://gitlab-ci-token:${RESULTS_REPO_TOKEN}@git.ecdf.ed.ac.uk/asimov/asimov-ccs-nightly-data.git
    - asimov-ccs-nightly-data/append_data.py asimov-ccs-nightly-data/performance_results.json tests/nightly/performance/output*.txt
    - cd asimov-ccs-nightly-data
    - git add performance_results.json
    - git -c user.name='CI' -c user.email='ci' commit -m "CI adds data"
    - git push



# 2 nodes
A2_perf_2nodes:
  extends: [.setup_A2_perf, .setup_cray_A2]
  variables:
    SLURM_partition: standard
    SLURM_qos: lowpriority
    SLURM_time: "00:10:00"
    SLURM_ntasks_per_node: 128
    SLURM_nodes: 2
  script:
    - CMP=cray make -j all
    - export CPS=136
    - export NCORES=256
    - RUNTESTS=nightly/performance/test_tgv.yaml CMP=cray make tests
  artifacts:
    paths: [tests/nightly/performance/output*txt]

A2_perf_2nodes_database_update:
  extends: [.setup_A2_perf, .setup_cray_A2]
  needs:
    - job: A2_perf_2nodes
      artifacts: true
  variables:
    ON_COMPUTE: "FALSE"
  script:
    - git clone https://gitlab-ci-token:${RESULTS_REPO_TOKEN}@git.ecdf.ed.ac.uk/asimov/asimov-ccs-nightly-data.git
    - asimov-ccs-nightly-data/append_data.py asimov-ccs-nightly-data/performance_results.json tests/nightly/performance/output*.txt
    - cd asimov-ccs-nightly-data
    - git add performance_results.json
    - git -c user.name='CI' -c user.email='ci' commit -m "CI adds data"
    - git push


#-----------------------------------------------------------------------------#
# Nightly tests on the CI desktop

.setup_nightly:
  only:
    variables:
      - $NIGHTLY
  dependencies: []
  allow_failure: true

nightly_gnu_performance:
  extends: [.setup_nightly, .setup_gnu]
  script:
    - build_tools/test_load.sh
    - HOME=${CI_HOME} CMP=gnu make
    - export CPS=90
    - export NCORES=26
    - HOME=${CI_HOME} RUNTESTS=nightly/performance CMP=gnu make tests
    - git clone https://gitlab-ci-token:${RESULTS_REPO_TOKEN}@git.ecdf.ed.ac.uk/asimov/asimov-ccs-nightly-data.git
    - asimov-ccs-nightly-data/append_data.py asimov-ccs-nightly-data/performance_results.json tests/nightly/performance/output*.txt  
    - cd asimov-ccs-nightly-data
    - git add performance_results.json
    - git -c user.name='CI' -c user.email='ci' commit -m "CI adds data"
    - git push

nightly_gnu_verification:
  needs:
    - job: nightly_gnu_performance
  extends: [.setup_nightly, .setup_gnu]
  script:
    - HOME=${CI_HOME} CMP=gnu make
    - HOME=${CI_HOME} RUNTESTS=nightly/verification CMP=gnu make tests

nightly_dummy:
  needs:
    - job: nightly_gnu_verification
  extends: [.setup_nightly, .setup_intel]
  script:
    - echo "just a test"
      #- HOME=${CI_HOME} RUNTESTS=nightly CMP=intel make tests
      #- git clone https://gitlab-ci-token:${RESULTS_REPO_TOKEN}@git.ecdf.ed.ac.uk/asimov/asimov-ccs-nightly-data.git
      #- asimov-ccs-nightly-data/append_data.py asimov-ccs-nightly-data/ccs_data.csv tests/nightly/*/output.txt  
      #- cd asimov-ccs-nightly-data
      #- git add ccs_data.csv
      #- git -c user.name='CI' -c user.email='ci' commit -m "CI adds data"
      #- git push

nightly_wiki_update:
  needs: 
    - job: nightly_dummy
  extends: [.setup_nightly]
  script:
    - git clone https://gitlab-ci-token:${WIKI_TOKEN}@git.ecdf.ed.ac.uk/asimov/asimov-ccs.wiki.git 
    - git clone https://gitlab-ci-token:${RESULTS_REPO_TOKEN}@git.ecdf.ed.ac.uk/asimov/asimov-ccs-nightly-data.git
    - cd asimov-ccs.wiki
    - ../asimov-ccs-nightly-data/plot_performance.py --datafile ../asimov-ccs-nightly-data/performance_results.json --outfile img/ci-performance-graph
    - git add img/ci-performance-graph*
    - git -c user.name='CI' -c user.email='ci' commit -m "CI updates graph"
    - git push
