.general_setup:
  before_script:

.setup_gnu:
  before_script:
    - source setup_gitlab_runner_env
    - HOME=${CI_HOME} source ${CI_HOME}ci_vm_setup/setup_gnu_env.sh
    - cd src

.setup_intel:
  before_script:
    - source setup_gitlab_runner_env
    - HOME=${CI_HOME} source ${CI_HOME}ci_vm_setup/setup_intel_env.sh
    - cd src

.setup_cray:
  before_script:
    - source setup_gitlab_runner_env
    - cd src

.test_common:
  artifacts:
    when: always
    reports:
      junit: testing/tests/report.xml
  

#-----------------------------------------------------------------------------#

build_ccs_gnu:
  extends: .setup_gnu
  script:
    - HOME=${CI_HOME} CMP=gnu make all

test_ccs_gnu:
  needs: 
    - job: build_ccs_gnu
      artifacts: false
  extends: 
    - .setup_gnu
    - .test_common
  script:
    - HOME=${CI_HOME} CMP=gnu make tests

#-----------------------------------------------------------------------------#

build_ccs_intel:
  extends: .setup_intel
  script:
    - HOME=${CI_HOME} CMP=intel make all

test_ccs_intel:
  needs: 
    - job: build_ccs_intel
      artifacts: false
  extends: 
    - .setup_intel
    - .test_common
  script:
    - HOME=${CI_HOME} CMP=intel make tests

#-----------------------------------------------------------------------------#

build_ccs_intelx:
  extends: .setup_intel
  script:
    - HOME=${CI_HOME} CMP=intelx make all

test_ccs_intelx:
  needs: 
    - job: build_ccs_intelx
      artifacts: false
  extends: 
    - .setup_intel
    - .test_common
  script:
    - HOME=${CI_HOME} CMP=intelx make tests

#-----------------------------------------------------------------------------#

build_ccs_cray:
  extends: .setup_cray
  script:
    - HOME=${CI_HOME} cray_run_command "CMP=cray make all"

test_ccs_cray:
  needs: 
    - job: build_ccs_cray
      artifacts: false
  extends: 
    - .setup_cray
    - .test_common
  script:
    - cray_run_command "slurmctld -vv -L $HOME/slurmdctld.log"
    - cray_run_command "slurmd -vv -L $HOME/slurmd.log"
    - HOME=${CI_HOME} cray_run_command "CMP=cray make tests"

#-----------------------------------------------------------------------------#

generate_code_docs:
  extends: .general_setup
  script:
    - cd src
    - make docs
    - make docs-latex
  artifacts:
    paths:
      - src/latex/refman.pdf
  allow_failure: true

generate_dev_guide:
  extends: .general_setup
  script:
    - cd dev_guide
    - make all
  artifacts:
    paths:
      - dev_guide/ccs_dev_guide.pdf
  allow_failure: true

#-----------------------------------------------------------------------------#

profile_ccs_gnu:
  needs: 
    - job: build_ccs_gnu
      artifacts: false
  extends: .setup_gnu
  script:
    - HOME=${CI_HOME} CMP=gnu PROFILE=yes make all
  artifacts:
    paths:
      - src/opt_info.txt
  allow_failure: true

profile_ccs_intel:
  needs: 
    - job: build_ccs_intel
      artifacts: false
  extends: .setup_intel
  script:
    - HOME=${CI_HOME} CMP=intel PROFILE=yes make all
  artifacts:
    paths:
      - src/obj/*.html
      - src/*.html
  allow_failure: true

profile_ccs_cray:
  needs: 
    - job: build_ccs_cray
      artifacts: false
  extends: .setup_cray
  script:
    - HOME=${CI_HOME} cray_run_command "CMP=cray PROFILE=yes make all"
  artifacts:
    paths:
      - src/obj/*.lst
      - src/*.lst
  allow_failure: true
