stages:
  - gnu_build
  - gnu_test
  - intel_build
  - intel_test
  - docs_generation

variables:
  CI_HOME: "/home/ubuntu/"


build_ccs_gnu:
  stage: gnu_build
  before_script:
    - HOME=${CI_HOME} source ${CI_HOME}ci_vm_setup/setup_gnu_env.sh
    - cd src
  script:
    - HOME=${CI_HOME} CMP=gnu make
    - mv ccs_app ccs_app_gnu
  artifacts:
    paths:
      - src/ccs_app_gnu
    expire_in: 10 minutes

test_ccs_gnu:
  stage: gnu_test
  before_script:
    - HOME=${CI_HOME} source ${CI_HOME}ci_vm_setup/setup_gnu_env.sh
    - cd src
  script:
    - HOME=${CI_HOME} mpirun --oversubscribe -n 4 ./ccs_app_gnu


build_ccs_intel:
  stage: intel_build
  before_script:
    - HOME=${CI_HOME} source ${CI_HOME}ci_vm_setup/setup_intel_env.sh
    - cd src
  script:
    - HOME=${CI_HOME} CMP=intel make
    - mv ccs_app ccs_app_intel
  artifacts:
    paths:
      - src/ccs_app_intel
    expire_in: 10 minutes

test_ccs_intel:
  stage: intel_test
  before_script:
    - HOME=${CI_HOME} source ${CI_HOME}ci_vm_setup/setup_intel_env.sh
    - cd src
  script:
    - HOME=${CI_HOME} mpirun -n 4 ./ccs_app_intel

generate_documentation:
  stage: docs_generation
  before_script:
    - cd src
  script:
    - make docs
