---
title: bc_test

boundaries:
  n_boundaries: 4
  boundary_1:
    name: left
    type: wall
    u: 107.345
 
  boundary_2:
    name: top
    type: periodic
 
  boundary_3:
    name: right
    type: dirichlet
    u: -5.0
 
  boundary_4:
    name: bottom
    type: periodic
