---
title: LidDrivenCavity

# "steps" - currently the number of iterations
steps: 10

relaxation_factor:
  u: 0.9
  v: 0.9
  p: 0.1

### VALUES BELOW THIS POINT ARE NOT CURRENTLY USED

#reference_numbers:
#    pressure: 101325.0
#    temperature: 289.0
#    density: 1.0
#    viscosity: 1.0e-03
#    pref_at_cell: 4096

#solve:
#  w: off

#init: 
#  type: user

#target_residual: 1.0e-10

#monitor_cell: 1990

# 1 = central
#convection_scheme:
#  u: 1 
#  v: 1
#  w: 1

#blending_factor:
#  u: 1.0
#  v: 1.0
#  w: 1.0
  
#output:
#  every: 1000

#post:
#  type: center
#  variables: [u, v, w, p]

variables:
  n_variables: 3
  variable_1:
    name: u
    type: central
  variable_2:
    name: v
    type: upwind
  variable_3:
    name: p
    type: central

boundaries:
  n_boundaries: 4
  boundary_1: 
    name: left
    id: 92749
    type: wall
    variable_u:
      type: wall
      value: 0
    variable_v:
      type: wall
      value: 0
  boundary_3:
    name: top
    id: 17648
    variable_u:
      type: dirichlet
      value: 1
    variable_v:
      type: wall
      value: 0
  boundary_2:
    name: right
    id: 0
    type: wall
    variable_u:
      type: wall
      value: 0
    variable_v:
      type: wall
      value: 0
  boundary_4:
    name: bottom
    id: 1
    type: wall
    variable_u:
      type: wall
      value: 0
    variable_v:
      type: wall
      value: 0